name: Build and test android APK

on:
    pull_request:
    push:
        branches:
            - main
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-java@v4
              with:
                  distribution: 'zulu' # Same as my PC
                  java-version: '17.x'
            - uses: subosito/flutter-action@v2
              with:
                  flutter-version: '3.22.0-0.1.pre'
                  channel: 'beta'
            - run: flutter config --no-analytics
            - run: flutter pub get
            - run: flutter build appbundle
